 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/families", type: :request do
  # Family. As you add validations to Family, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Family.create! valid_attributes
      get families_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      family = Family.create! valid_attributes
      get family_url(family)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_family_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      family = Family.create! valid_attributes
      get edit_family_url(family)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Family" do
        expect {
          post families_url, params: { family: valid_attributes }
        }.to change(Family, :count).by(1)
      end

      it "redirects to the created family" do
        post families_url, params: { family: valid_attributes }
        expect(response).to redirect_to(family_url(Family.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Family" do
        expect {
          post families_url, params: { family: invalid_attributes }
        }.to change(Family, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post families_url, params: { family: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested family" do
        family = Family.create! valid_attributes
        patch family_url(family), params: { family: new_attributes }
        family.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the family" do
        family = Family.create! valid_attributes
        patch family_url(family), params: { family: new_attributes }
        family.reload
        expect(response).to redirect_to(family_url(family))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        family = Family.create! valid_attributes
        patch family_url(family), params: { family: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested family" do
      family = Family.create! valid_attributes
      expect {
        delete family_url(family)
      }.to change(Family, :count).by(-1)
    end

    it "redirects to the families list" do
      family = Family.create! valid_attributes
      delete family_url(family)
      expect(response).to redirect_to(families_url)
    end
  end
end
