 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/forests", type: :request do
  # Forest. As you add validations to Forest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Forest.create! valid_attributes
      get forests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      forest = Forest.create! valid_attributes
      get forest_url(forest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_forest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      forest = Forest.create! valid_attributes
      get edit_forest_url(forest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Forest" do
        expect {
          post forests_url, params: { forest: valid_attributes }
        }.to change(Forest, :count).by(1)
      end

      it "redirects to the created forest" do
        post forests_url, params: { forest: valid_attributes }
        expect(response).to redirect_to(forest_url(Forest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Forest" do
        expect {
          post forests_url, params: { forest: invalid_attributes }
        }.to change(Forest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post forests_url, params: { forest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested forest" do
        forest = Forest.create! valid_attributes
        patch forest_url(forest), params: { forest: new_attributes }
        forest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the forest" do
        forest = Forest.create! valid_attributes
        patch forest_url(forest), params: { forest: new_attributes }
        forest.reload
        expect(response).to redirect_to(forest_url(forest))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        forest = Forest.create! valid_attributes
        patch forest_url(forest), params: { forest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested forest" do
      forest = Forest.create! valid_attributes
      expect {
        delete forest_url(forest)
      }.to change(Forest, :count).by(-1)
    end

    it "redirects to the forests list" do
      forest = Forest.create! valid_attributes
      delete forest_url(forest)
      expect(response).to redirect_to(forests_url)
    end
  end
end
